# Site settings
title:       Explorando - Un blog de Daniel Villanueva
email:       dvillaj@gmail.com	
author:      Daniel Villanueva
description: "Explorador intrepido y eterno aprendiz"
baseurl:     ""
url:         "https://dvillaj.github.io"
date_format: "%-d-%b-%Y"

# Google services
google_analytics: 
google_verification: UA-62530238-3

# Optional features
animated:             false
show_related_posts:   true
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: dvillaj
bitbucket_username:
stackoverflow_id:
twitter_username: dvillaj
google_plus_id:
linkedin_username: dvillaj
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
